# Setup
title:        张铁的博客
tagline:      基础知识/算法题/项目笔记
baseurl:      ""
paginate:     1
locale:       "cn"

# About/contact
author:
  name:       tie zhang
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
plugins: [jekyll-paginate]

defaluts:
  -
    scope:
      path: ""
      values: 
        layout: "post"
        author: 张铁